### ISSUE TITLE
Cannot run /detector add with full permissions

### ISSUE THREAD

**Issue by 9hNk** [BadPingHere/dernal#2]
![Discord_7lg419bJ9w](https://github.com/user-attachments/assets/3f86e7f8-80d1-42e9-a1a1-32203d4f3b08)

As the server owner, and with the bot having all permissions, I do not have permission to do "/detector add channel: #... guild_prefix: ..."

**Comment by BadPingHere** [comment]
This is intended behavior, as we cannot sustain the API requests of multiple servers using detector at once. Though I can admit that the message is vague and should be elaborated on. Currently, until we get our own API key (never), to use Detector you will need to self-host.
